/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión
         * @description La web recibe una cookie de sesión; los clientes nativos piden `token` y lo envían como Bearer.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cerrar sesión */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuario actual y sus organizaciones */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/brands": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /** Marcas de la organización */
        get: operations["listBrands"];
        put?: never;
        /** Crear una marca */
        post: operations["createBrand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        /** Cuentas conectadas a la marca */
        get: operations["listAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/accounts/connect": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar la conexión OAuth con una red
         * @description Devuelve la URL de autorización de la red. El cliente la abre; la red redirige al callback del servidor.
         */
        post: operations["startAccountConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/{network}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retorno de la red tras autorizar */
        get: operations["oauthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Desconectar una cuenta
         * @description Revoca el token y borra sus datos según la política de retención.
         */
        delete: operations["disconnectAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pedir una sincronización ahora */
        post: operations["requestSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diccionario de métricas
         * @description Definición propia de cada métrica y la nativa de cada red, con su vigencia.
         */
        get: operations["listMetricDefinitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/summary": {
        parameters: {
            query: {
                from: components["parameters"]["From"];
                to: components["parameters"]["To"];
                /** @description `previous` compara con el periodo inmediatamente anterior de igual duración. */
                compare?: components["parameters"]["Compare"];
                /** @description Redes a incluir; sin el parámetro, todas las conectadas. */
                networks?: components["parameters"]["Networks"];
            };
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        /**
         * Resumen de marca
         * @description Indicadores del periodo con su comparación, desglose por red, índice de formato y la lectura del agente si existe.
         */
        get: operations["getBrandSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/timeseries": {
        parameters: {
            query: {
                from: components["parameters"]["From"];
                to: components["parameters"]["To"];
                /** @description `previous` compara con el periodo inmediatamente anterior de igual duración. */
                compare?: components["parameters"]["Compare"];
                /** @description Redes a incluir; sin el parámetro, todas las conectadas. */
                networks?: components["parameters"]["Networks"];
                metric: string;
                granularity?: "day" | "week";
            };
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        /** Serie temporal de una métrica */
        get: operations["getTimeseries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        /** Anotaciones sobre la línea de tiempo */
        get: operations["listAnnotations"];
        put?: never;
        /** Añadir una anotación */
        post: operations["createAnnotation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/posts": {
        parameters: {
            query: {
                from: components["parameters"]["From"];
                to: components["parameters"]["To"];
                /** @description Redes a incluir; sin el parámetro, todas las conectadas. */
                networks?: components["parameters"]["Networks"];
                format?: components["schemas"]["PostFormat"][];
                pillar?: string;
                /** @description Métrica de orden; un guion delante invierte a mayor primero. */
                sort?: string;
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        /** Publicaciones del periodo */
        get: operations["listPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{postId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        /** Detalle de una publicación */
        get: operations["getPost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/briefings/latest": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        /** Briefing semanal más reciente */
        get: operations["getLatestBriefing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/alerts": {
        parameters: {
            query?: {
                /** @description Solo las no atendidas. */
                open?: boolean;
            };
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        /** Alertas de la marca */
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/ollama-keys": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /**
         * Estado de las claves
         * @description Nunca devuelve la clave; solo sus cuatro últimos caracteres y su estado.
         */
        get: operations["listOllamaKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/ollama-keys/{scope}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                /** @description `org` exige rol de administrador; `user` es la clave personal de quien llama. */
                scope: components["schemas"]["KeyScope"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Registrar o reemplazar una clave
         * @description El servidor la valida contra Ollama Cloud, la cifra y revoca la anterior del mismo alcance.
         */
        put: operations["setOllamaKey"];
        post?: never;
        /** Revocar una clave */
        delete: operations["revokeOllamaKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/agent/models": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /**
         * Modelos disponibles con la clave en uso
         * @description Se descubren en Ollama Cloud y se guardan en caché; no hay lista fija en el servidor. Solo aparecen los que declaran visión, herramientas y razonamiento.
         */
        get: operations["listAgentModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/agent/queue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /** Cola del agente */
        get: operations["getAgentQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/agent/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        /** Conversaciones de la marca */
        get: operations["listConversations"];
        put?: never;
        /** Abrir una conversación con su primera pregunta */
        post: operations["createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/conversations/{conversationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        /** Conversación con todas sus ejecuciones */
        get: operations["getConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/conversations/{conversationId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hacer otra pregunta en la conversación */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /** Estado y resultado de una ejecución */
        get: operations["getRun"];
        put?: never;
        post?: never;
        /** Cancelar una ejecución en cola o en curso */
        delete: operations["cancelRun"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: {
                /** @description Reanuda desde el evento siguiente al indicado tras una reconexión. */
                "Last-Event-ID"?: string;
            };
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /**
         * Progreso de una ejecución en streaming
         * @description Server-Sent Events. Cada evento lleva `id`, `event` y `data` en JSON con la forma de `AgentEvent`.
         *     Orden habitual: `run.queued` → `run.started` → `thinking.delta`* → (`tool.call` → `tool.result`)* →
         *     `answer.delta`* → `citation`* → `run.completed`. El flujo se cierra tras `run.completed`,
         *     `run.failed` o `run.cancelled`. Una ejecución ya terminada reproduce sus eventos y cierra.
         */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /**
             * @description Código estable para que el cliente decida qué mostrar.
             * @example no_ollama_key
             * @example ollama_key_rejected
             * @example period_too_long
             */
            code?: string;
            errors?: {
                field: string;
                message: string;
            }[];
        };
        /**
         * @default web
         * @enum {string}
         */
        ClientKind: "web" | "android" | "ios" | "macos";
        /** @enum {string} */
        Network: "instagram" | "facebook" | "tiktok" | "youtube" | "linkedin" | "x";
        /** @enum {string} */
        PostFormat: "reel" | "carousel" | "image" | "story" | "video" | "short" | "text" | "link";
        /** @enum {string} */
        MemberRole: "owner" | "admin" | "analyst" | "editor" | "viewer";
        /** @enum {string} */
        KeyScope: "org" | "user";
        /** @enum {string} */
        AgentMode: "analyst" | "briefing" | "sentinel" | "auditor" | "writer";
        /** @enum {string} */
        RunStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
        };
        Membership: {
            /** Format: uuid */
            org_id: string;
            org_name: string;
            role: components["schemas"]["MemberRole"];
            has_org_ollama_key: boolean;
            has_user_ollama_key: boolean;
        };
        Brand: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            org_id: string;
            name: string;
            slug: string;
            timezone: string;
            voice?: string | null;
            /** @description Redes con al menos una cuenta propia conectada. */
            networks: components["schemas"]["Network"][];
            /** @description Titular del último briefing, para la lista de la cartera. */
            week_headline?: string | null;
        };
        SocialAccount: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            brand_id: string;
            network: components["schemas"]["Network"];
            handle: string;
            display_name?: string | null;
            is_competitor: boolean;
            /** @enum {string} */
            status: "active" | "needs_reauth" | "paused" | "disconnected";
            /** Format: date-time */
            last_synced_at?: string | null;
            /**
             * Format: date
             * @description Último día con datos completos; algunas redes entregan con retraso.
             */
            data_through?: string | null;
            last_error?: string | null;
        };
        MetricDefinition: {
            key: string;
            label: string;
            /** @enum {string} */
            unit: "count" | "percent" | "seconds" | "minutes" | "currency";
            /** @enum {string} */
            rollup: "sum" | "last" | "avg";
            description: string;
            networks: {
                network: components["schemas"]["Network"];
                native_name: string;
                definition: string;
                /** Format: date */
                valid_from: string;
                /** Format: date */
                valid_to?: string | null;
            }[];
        };
        Period: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
        };
        Kpi: {
            metric: string;
            value: number;
            /** @enum {string} */
            unit: "count" | "percent" | "seconds" | "minutes" | "currency";
            previous?: number | null;
            /** @description Variación relativa (0.184 = +18,4 %); en métricas porcentuales, diferencia en puntos. */
            delta?: number | null;
            /** @enum {string} */
            delta_kind?: "relative" | "points" | "absolute";
            /** @description Falso en métricas donde bajar es mejorar (p. ej. bajas o tiempo de respuesta). */
            up_is_good: boolean;
            /** @description Doce valores semanales que terminan en el periodo actual. */
            sparkline?: number[];
        };
        /** @description Frase de lectura del agente con la que abre cada vista. */
        Insight: {
            text: string;
            /** Format: uuid */
            run_id: string;
            /** Format: date-time */
            generated_at: string;
        };
        BrandSummary: {
            period: components["schemas"]["Period"];
            compare_period?: components["schemas"]["Period"] | null;
            insight?: components["schemas"]["Insight"];
            kpis: components["schemas"]["Kpi"][];
            by_network: {
                network: components["schemas"]["Network"];
                metric: string;
                value: number;
                delta?: number | null;
            }[];
            /** @description Alcance mediano de cada formato dividido entre la mediana de la cuenta. */
            format_index: {
                format: components["schemas"]["PostFormat"];
                posts: number;
                index: number;
            }[];
            account_median_reach?: number | null;
        };
        Timeseries: {
            metric: string;
            /** @enum {string} */
            unit: "count" | "percent" | "seconds" | "minutes" | "currency";
            /** @enum {string} */
            granularity: "day" | "week";
            points: {
                /** Format: date */
                date: string;
                /** @description Nulo si la red aún no entregó ese día. */
                value: number | null;
                /** Format: date */
                previous_date?: string | null;
                previous_value?: number | null;
            }[];
        };
        Annotation: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            occurred_on: string;
            label: string;
            /** Format: uuid */
            post_id?: string | null;
        };
        PostRow: {
            /** Format: uuid */
            id: string;
            network: components["schemas"]["Network"];
            format: components["schemas"]["PostFormat"];
            /** Format: date-time */
            published_at: string;
            title?: string | null;
            /** Format: uri */
            permalink?: string | null;
            /** Format: uri */
            thumbnail_url?: string | null;
            pillar?: string | null;
            /**
             * @description Último valor de cada métrica; falta la clave si la red no la ofrece.
             * @example {
             *       "reach": 14800,
             *       "likes": 902,
             *       "comments": 77,
             *       "shares": 187,
             *       "saves": 312
             *     }
             */
            metrics: {
                [key: string]: number;
            };
            /** @description Interacciones entre alcance (0.094 = 9,4 %). */
            engagement_rate?: number | null;
            /** @description Alcance de la pieza entre la mediana de la cuenta (3.2 = 3,2×). */
            vs_median?: number | null;
            /** @description Alcance acumulado cada 6 horas durante las primeras 72; 13 valores. */
            life_curve_72h?: number[];
        };
        PostDetail: components["schemas"]["PostRow"] & {
            caption?: string | null;
            duration_seconds?: number | null;
            life_curve: {
                metric: string;
                points: components["schemas"]["CurvePoint"][];
                /** @description La misma curva para la pieza mediana de la cuenta. */
                median_points: components["schemas"]["CurvePoint"][];
            };
            creative_reading?: {
                items: {
                    /**
                     * @example Gancho
                     * @example Texto
                     * @example Ritmo
                     */
                    aspect: string;
                    text: string;
                }[];
                model: string;
                /** Format: uuid */
                run_id: string;
            } | null;
        };
        CurvePoint: {
            /** @description Horas desde la publicación. */
            hours: number;
            value: number;
        };
        OllamaKey: {
            scope: components["schemas"]["KeyScope"];
            last4: string;
            max_concurrency: number;
            /** Format: date-time */
            validated_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        AgentModel: {
            name: string;
            /** @description Valores que el modelo admite en `think`; vacío si no razona. */
            thinking: string[];
            thinking_default?: string | null;
            tools: boolean;
            vision: boolean;
            /** @description Verdadero si el modelo declara entrada de audio. No es requisito para aparecer en la lista. */
            audio?: boolean;
        };
        AgentQueue: {
            key_scope: components["schemas"]["KeyScope"];
            max_concurrency: number;
            running: components["schemas"]["QueueItem"][];
            queued: components["schemas"]["QueueItem"][];
        };
        QueueItem: {
            /** Format: uuid */
            run_id: string;
            mode: components["schemas"]["AgentMode"];
            brand_name: string;
            /** Format: date-time */
            queued_at: string;
        };
        Conversation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            brand_id: string;
            title: string;
            mode: components["schemas"]["AgentMode"];
            /** Format: date-time */
            created_at: string;
        };
        NewMessage: {
            question: string;
            mode?: components["schemas"]["AgentMode"];
            /** @description Sin él, el servidor elige según la tarea. */
            model?: string;
            /** @description Nivel de razonamiento entre los que admite el modelo. */
            think?: string;
            /** @description Lo que el usuario tenía en pantalla al preguntar. */
            context?: {
                period?: components["schemas"]["Period"];
                networks?: components["schemas"]["Network"][];
                /** Format: uuid */
                post_id?: string;
                /** @description Identificador del gráfico sobre el que se pregunta. */
                chart?: string;
            };
        };
        AgentRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversation_id?: string | null;
            mode: components["schemas"]["AgentMode"];
            status: components["schemas"]["RunStatus"];
            model: string;
            think?: string | null;
            key_scope: components["schemas"]["KeyScope"];
            question: string;
            thinking?: string | null;
            answer?: string | null;
            tool_calls?: components["schemas"]["ToolCall"][];
            citations?: components["schemas"]["Citation"][];
            /** @description Gráficos que el agente adjunta a su respuesta. */
            attachments?: components["schemas"]["RunAttachment"][];
            /** Format: date-time */
            queued_at: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /** @description Tokens de entrada sumados en todas las vueltas. */
            prompt_tokens?: number | null;
            /** @description Tokens generados sumados en todas las vueltas. */
            completion_tokens?: number | null;
            error?: string | null;
        };
        /** @description Gráfico de columnas que acompaña a una respuesta; cada punto sale de la consulta que cita `ref`. */
        RunAttachment: {
            /** @enum {string} */
            kind: "columns";
            title: string;
            /** @enum {string} */
            unit?: "count" | "percent" | "seconds" | "minutes" | "currency";
            /** @description Número [n] de la cita que respalda el gráfico. */
            ref?: number | null;
            points: {
                label: string;
                value: number;
                highlight?: boolean;
            }[];
        };
        ToolCall: {
            seq: number;
            tool: string;
            arguments: {
                [key: string]: unknown;
            };
            result_summary?: string | null;
            duration_ms?: number | null;
        };
        /** @description Vincula un [n] del texto con la consulta que produjo la cifra. */
        Citation: {
            ref: number;
            label: string;
            tool: string;
            query: {
                [key: string]: unknown;
            };
        };
        Briefing: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            brand_id: string;
            /** Format: date */
            week_start: string;
            headline: string;
            kpis: components["schemas"]["Kpi"][];
            findings: {
                title: string;
                evidence: string;
                /** @description A qué vista lleva «ver evidencia». */
                link?: {
                    /** @enum {string} */
                    view: "summary" | "posts" | "post" | "agent_run";
                    /** Format: uuid */
                    id?: string;
                };
            }[];
            recommendation?: string | null;
            /** Format: uuid */
            run_id: string;
            /** Format: date-time */
            created_at: string;
        };
        Alert: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            severity: "warning" | "serious" | "critical";
            network?: components["schemas"]["Network"] | null;
            metric?: string | null;
            /** Format: date */
            occurred_on: string;
            title: string;
            diagnosis?: string | null;
            /** Format: uuid */
            post_id?: string | null;
            /** Format: uuid */
            run_id?: string | null;
            /** Format: date-time */
            acknowledged_at?: string | null;
        };
        /** @description Carga del campo `data` de cada evento del flujo. */
        AgentEvent: {
            /** @enum {string} */
            type: "run.queued" | "run.started" | "run.cancelled";
            /** @description Puesto en la cola; solo en `run.queued`. */
            position?: number;
        } | {
            /** @enum {string} */
            type: "thinking.delta" | "answer.delta";
            text: string;
        } | {
            /** @constant */
            type: "tool.call";
            seq: number;
            tool: string;
            arguments: {
                [key: string]: unknown;
            };
        } | {
            /** @constant */
            type: "tool.result";
            seq: number;
            summary: string;
            duration_ms?: number;
        } | {
            /** @constant */
            type: "citation";
            citation: components["schemas"]["Citation"];
        } | {
            /** @constant */
            type: "run.completed";
            run: components["schemas"]["AgentRun"];
        } | {
            /** @constant */
            type: "run.failed";
            error: string;
            /**
             * @example ollama_unavailable
             * @example ollama_key_rejected
             * @example tool_error
             */
            code?: string;
        };
    };
    responses: {
        /** @description Sin sesión válida. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description El rol no permite esta operación. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No existe o no pertenece a una organización del usuario. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Parámetros o cuerpo no válidos. */
        Invalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Demasiadas peticiones; reintente tras `Retry-After`. */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No hay clave de Ollama utilizable, ni personal ni de la agencia. */
        NoOllamaKey: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        OrgId: string;
        BrandId: string;
        AccountId: string;
        PostId: string;
        ConversationId: string;
        RunId: string;
        From: string;
        To: string;
        /** @description `previous` compara con el periodo inmediatamente anterior de igual duración. */
        Compare: "none" | "previous";
        /** @description Redes a incluir; sin el parámetro, todas las conectadas. */
        Networks: components["schemas"]["Network"][];
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** Format: password */
                    password: string;
                    client?: components["schemas"]["ClientKind"];
                };
            };
        };
        responses: {
            /** @description Sesión creada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                        /** Format: date-time */
                        expires_at: string;
                        /** @description Solo para clientes nativos. */
                        token?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión revocada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuario, pertenencias y estado de sus claves. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                        memberships: components["schemas"]["Membership"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listBrands: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marcas activas, con su titular de la semana si existe. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Brand"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createBrand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @default America/Guayaquil */
                    timezone?: string;
                    voice?: string;
                };
            };
        };
        responses: {
            /** @description Marca creada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Invalid"];
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cuentas propias y de la competencia, con su estado de sincronización. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SocialAccount"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    startAccountConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    network: components["schemas"]["Network"];
                    /**
                     * Format: uri
                     * @description Dónde vuelve el usuario al terminar; debe pertenecer a un origen permitido.
                     */
                    return_url: string;
                };
            };
        };
        responses: {
            /** @description URL de autorización. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        authorize_url: string;
                        state: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Invalid"];
        };
    };
    oauthCallback: {
        parameters: {
            query: {
                code?: string;
                state: string;
                error?: string;
            };
            header?: never;
            path: {
                network: components["schemas"]["Network"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirige a `return_url` con `connected=<accountId>` o `error=<código>`. */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Invalid"];
        };
    };
    disconnectAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cuenta desconectada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    requestSync: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sincronización en cola. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        sync_run_id: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listMetricDefinitions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Diccionario completo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["MetricDefinition"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getBrandSummary: {
        parameters: {
            query: {
                from: components["parameters"]["From"];
                to: components["parameters"]["To"];
                /** @description `previous` compara con el periodo inmediatamente anterior de igual duración. */
                compare?: components["parameters"]["Compare"];
                /** @description Redes a incluir; sin el parámetro, todas las conectadas. */
                networks?: components["parameters"]["Networks"];
            };
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resumen del periodo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Invalid"];
        };
    };
    getTimeseries: {
        parameters: {
            query: {
                from: components["parameters"]["From"];
                to: components["parameters"]["To"];
                /** @description `previous` compara con el periodo inmediatamente anterior de igual duración. */
                compare?: components["parameters"]["Compare"];
                /** @description Redes a incluir; sin el parámetro, todas las conectadas. */
                networks?: components["parameters"]["Networks"];
                metric: string;
                granularity?: "day" | "week";
            };
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Serie del periodo y, si se pidió, la del periodo de comparación alineada punto a punto. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeseries"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Invalid"];
        };
    };
    listAnnotations: {
        parameters: {
            query: {
                from: components["parameters"]["From"];
                to: components["parameters"]["To"];
            };
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Anotaciones del periodo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Annotation"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createAnnotation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date */
                    occurred_on: string;
                    label: string;
                    /** Format: uuid */
                    post_id?: string;
                };
            };
        };
        responses: {
            /** @description Anotación creada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Annotation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Invalid"];
        };
    };
    listPosts: {
        parameters: {
            query: {
                from: components["parameters"]["From"];
                to: components["parameters"]["To"];
                /** @description Redes a incluir; sin el parámetro, todas las conectadas. */
                networks?: components["parameters"]["Networks"];
                format?: components["schemas"]["PostFormat"][];
                pillar?: string;
                /** @description Métrica de orden; un guion delante invierte a mayor primero. */
                sort?: string;
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Publicaciones con sus métricas más recientes y su relación con la mediana de la cuenta. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PostRow"][];
                        total: number;
                        /** @description Pilares con publicaciones en el periodo y las redes elegidas, sin aplicar los filtros de formato ni pilar; alimentan los selectores. */
                        available_pillars: string[];
                        /** @description Formatos con publicaciones en el periodo y las redes elegidas, sin aplicar los filtros de formato ni pilar. */
                        available_formats: components["schemas"]["PostFormat"][];
                        account_median_reach: number | null;
                        insight?: components["schemas"]["Insight"];
                        next_cursor: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Invalid"];
        };
    };
    getPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Publicación con métricas, curva de vida y lectura creativa. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getLatestBriefing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Briefing de la última semana cerrada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Briefing"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                /** @description Solo las no atendidas. */
                open?: boolean;
            };
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alertas con su diagnóstico. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Alert"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listOllamaKeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clave de la agencia y clave personal del usuario, si existen. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        org_key: components["schemas"]["OllamaKey"] | null;
                        user_key: components["schemas"]["OllamaKey"] | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    setOllamaKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                /** @description `org` exige rol de administrador; `user` es la clave personal de quien llama. */
                scope: components["schemas"]["KeyScope"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: password */
                    api_key: string;
                    /** @description Peticiones simultáneas que permite el plan de esa clave. Por defecto, 1. */
                    max_concurrency?: number;
                };
            };
        };
        responses: {
            /** @description Clave validada y guardada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OllamaKey"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Ollama Cloud rechazó la clave o no respondió. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    revokeOllamaKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                /** @description `org` exige rol de administrador; `user` es la clave personal de quien llama. */
                scope: components["schemas"]["KeyScope"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clave revocada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAgentModels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Modelos con sus capacidades. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AgentModel"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAgentQueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ocupación de la clave que usaría quien llama y tareas en curso o en espera. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentQueue"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["NoOllamaKey"];
        };
    };
    listConversations: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversaciones, la más reciente primero. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Conversation"][];
                        next_cursor: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: components["parameters"]["BrandId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewMessage"];
            };
        };
        responses: {
            /** @description Conversación creada y ejecución en cola. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        conversation: components["schemas"]["Conversation"];
                        run: components["schemas"]["AgentRun"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["NoOllamaKey"];
            422: components["responses"]["Invalid"];
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversación completa. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        conversation: components["schemas"]["Conversation"];
                        runs: components["schemas"]["AgentRun"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewMessage"];
            };
        };
        responses: {
            /** @description Ejecución en cola; siga su progreso en `/agent/runs/{runId}/events`. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRun"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["NoOllamaKey"];
            422: components["responses"]["Invalid"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ejecución con razonamiento, herramientas, respuesta y citas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRun"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description La ejecución ya había terminado. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Reanuda desde el evento siguiente al indicado tras una reconexión. */
                "Last-Event-ID"?: string;
            };
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flujo de eventos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
